# Generated by Django 5.2.4 on 2025-08-09 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_subpost_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_subposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
