# Generated by Django 5.2.4 on 2025-08-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpost',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
