# Generated by Django 5.2.4 on 2025-08-09 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_subpost_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subposts', to='blog.post'),
        ),
    ]
